Activity/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('addactivity/', views.addactivity, name='addactivity'),
    path('saveactivity/', views.saveactivity, name='saveactivity'),
    path('deleteactivity/', views.deleteactivity, name='deleteactivity'),
]

Home/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index),
]

MyProfile/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('profile/', include('MyProfile.urls')),
    path('activity/', include(('Activity.urls', 'Activity'), namespace='activity')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Activity/models.py
from django.db import models
from datetime import date

# Create your models here.
class Activity(models.Model):
	name = models.CharField(max_length=50)
	place = models.TextField()
	category = models.CharField(max_length=20)
	tanggal = models.DateField(default=date.today)
	time = models.TimeField(default=date.today)

	def __str__(self):
		return "{}".format(self.name)

Home/models.py
from django.db import models

# Create your models here.

MyProfile/models.py
from django.db import models

# Create your models here.

Activity/forms.py
from django import forms

class Add_Activity(forms.Form):
	error_messagges = {
		'required': "Please fill in this field",
	}

	name_attrs = {
		'class': 'form-group form-control',
		'type': 'text',
		'placeholder': 'name your activity',
	}

	place_attrs = {
		'class': 'form-group form-control',
		'type': 'text',
		'placeholder': 'activity location',
	}

	category_attrs = {
		'class': 'form-group form-control',
		'type': 'text',
		'placeholder': 'activity category',
	}

	tanggal_attrs = {
		'class': 'form-group form-control',
		'type': 'date',
	}

	time_attrs = {
		'class': 'form-group form-control',
		'type': 'time',
	}

	name = forms.CharField(label="Activity Name", required= True, max_length=50, widget=forms.TextInput(attrs=name_attrs))
	place = forms.CharField(label="Location", required= True, widget=forms.TextInput(attrs=place_attrs))
	category = forms.CharField(label="Category", required= True, max_length=20, widget=forms.TextInput(attrs=category_attrs))
	tanggal = forms.DateField(label="Date", required=True, widget=forms.DateInput(attrs=tanggal_attrs))
	time = forms.TimeField(label="Time", required=True, widget=forms.TimeInput(attrs=time_attrs))

Activity/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .models import Activity
from .forms import Add_Activity

# Create your views here.
response = {}
html = 'activity.html'

def index(request):
	activities = Activity.objects.all()
	response['activities'] = activities

	html = 'activity.html'
	return render(request, html, response)

def addactivity(request):
	response['addactivity_forms'] = Add_Activity

	html = 'addactivity.html'
	return render(request, html, response)

def saveactivity(request):
	form = Add_Activity(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['place'] = request.POST['place']
		response['category'] = request.POST['category']
		response['tanggal'] = request.POST['tanggal']
		response['time'] = request.POST['time']
		activity = Activity(name=response['name'], place=response['place'],
			category=response['category'], tanggal=response['tanggal'], time=response['time'])
		activity.save()
		return HttpResponseRedirect('/activity/')
	else:
		return HttpResponseRedirect('/')

def deleteactivity(request):
	for activity in Activity.objects.all():
		activity.delete()
	return HttpResponseRedirect('/activity/')

Home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, "home.html")

MyProfile/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, "profile.html")

templates/activity.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Mikhael's Activity</title>
  </head>
  <body style="background-color: #00659b">
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
      <div class="container-fluid">
        <img src="{% static 'img/mikhael.jpg' %}" class="rounded-circle navbar-brand">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-menu navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile/">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/activity/">Activity</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div>
      <h1 class="display-4 text-center" style="font-variant: small-caps;">My Activity</h1>
    </div>

    <div id="activitybutton">
      <a href="{% url 'activity:addactivity' %}" class="btn btn-outline-light">Add Activity</a>
      <a href="{% url 'activity:deleteactivity' %}" class="btn btn-outline-warning">Delete All Activities</a>
    </div>
    
    {% if activities %}
    <div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope='col'>Activity</th>
            <th scope='col'>Place</th>
            <th scope='col'>Category</th>
            <th scope='col'>Date</th>
            <th scope='col'>Time</th>
          </tr>
        </thead>
        <tbody>
        {% for activity in activities %}
          <tr>
            <td>{{ activity.name }}</td>
            <td>{{ activity.place }}</td>
            <td>{{ activity.category }}</td>
            <td>{{ activity.time }}</td>
            <td>{{ activity.tanggal }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/addactivity.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Mikhael's Activity</title>
  </head>
  <body style="background-color: #00659b">
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
      <div class="container-fluid">
        <img src="{% static 'img/mikhael.jpg' %}" class="rounded-circle navbar-brand">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-menu navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile/">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/activity/">Activity</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- activity form -->
    <form action="{% url 'activity:saveactivity' %}" method="post">
      {% csrf_token %}
      {{ addactivity_forms }}

      <!--<div class="form-group">
        <label for="inputName">Name</label>
        <input type="text" class="form-control" id="inputName" placeholder="Enter your name">
      </div>
      <div class="form-group">
        <label for="inputDate">Date</label>
        <input type="text" class="form-control" id="inputDate" placeholder="Date format: dd-mm-yyyy">
      </div>
      <div class="form-group">
        <label for="inputEmail">Email</label>
        <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="Enter your email">
      </div>
      <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" placeholder="Password must have at least 8 characters">
      </div>
      <div class="form-group">
        <label for="confirmPassword">Confirmation Password</label>
        <input type="password" class="form-control" id="confirmPassword" placeholder="Enter the same password">
      </div>-->
      
      <button type="submit" class="btn btn-outline-light" value="Submit">Submit</button>
    </form>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Mikhael</title>
  </head>
  <body style="background-color: white">
    <!-- Jumbotron as introductory -->
    <div class="jumbotron-fluid text-center">
      <img src="{% static 'img/mikhael.jpg' %}" class="rounded-circle">
      <h1 class="display-4" style="font-variant: small-caps;">Mikhael</h1>
      <p class="lead">I am a Computer Science Student at Universitas Indonesia</p>
    </div>

    <!-- Home menu -->
    <p class="lead text-center" style="font-size: 200%; color: #00659b">learn more about me</p>
    <div class="home-menu text-center">
      <a href="/">Home</a>
      <a href="/profile/">Profile</a>
      <a href="/activity/">Activity</a>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/profile.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Mikhael's Profile</title>
  </head>
  <body style="background-color: #00659b">
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
      <div class="container-fluid">
        <img src="{% static 'img/mikhael.jpg' %}" class="rounded-circle navbar-brand">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-menu navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile/">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/activity/">Activity</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- name and profile picture -->
    <section class="profile-pict">
      <div class="container text-center">
        <div class="row pt-5">
          <div class="col-md">
            <img src="{% static 'img/mikhael.jpg' %}" class="rounded-circle">
          </div>
        </div>
        <div class="row">
          <div class="col-md">
            <h1 class="display-4" style="font-variant: small-caps;">Mikhael</h1>
            <hr>
          </div>
        </div>
      </div>
    </section>


    <!-- main profile -->
    <section class="profile">
      <div class="container text-justify">
        <div class="row my-1">
          <div class="col-md-3"><p>Birth</p></div>
          <div class="col-md-6"><p>Jakarta, 2 May 1999</p></div>
        </div>
        <hr>
        <div class="row my-1">
          <div class="col-md-3"><p>Address</p></div>
          <div class="col-md-6"><p>Jl. Kejayaan Dalam no. 57 Krukut, Taman Sari, Jakarta Barat</p></div>
        </div>
        <hr>
        <div class="row my-1">
          <div class="col-md-3"><p>Phone Number</p></div>
          <div class="col-md-6"><p>085286634487</p></div>
        </div>
        <hr>
        <div class="row my-1">
          <div class="col-md-3"><p>E-mail</p></div>
          <div class="col-md-6"><p>mikhaelbuntaran@gmail.com</p></div>
        </div>
      </div>
    </section>

    <!-- skills and hobbies -->
    <div class="center blue-font">
      <div class="card small-card">
        <div class="card-header">Skills</div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            teamwork and leadership
          </li>
          <li class="list-group-item">
            html and css
          </li>
          <li class="list-group-item">
            python
          </li>
          <li class="list-group-item">
            java
          </li>
        </ul>
      </div>
      <div class="card small-card">
        <div class="card-header">Hobbies</div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            listening to music
          </li>
          <li class="list-group-item">
            playing video games
          </li>
          <li class="list-group-item">
            reading
          </li>
          <li class="list-group-item">
            watching movies
          </li>
        </ul>
      </div>
    </div>

    <!-- education -->
    <div class="center">
      <div class="card big-card">
        <div class="card-header">Education</div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <p>2017 - now</p>
            <p>Faculty of Computer Science, Universitas Indonesia</p>
          </li>
          <li class="list-group-item">
            <p>2014 - 2017</p>
            <p>Ketapang High School</p>
          </li>
          <li class="list-group-item">
            <p>2011 - 2014</p>
            <p>Ketapang Junior High School</p>
          </li>
          <li class="list-group-item">
            <p>2005 - 2011</p>
            <p>Haleluya Elementary School</p>
          </li>
        </ul>
      </div>
    </div>

    <!-- experiences -->
    <div class="center">
      <div class="card big-card">
        <div class="card-header">Experiences</div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <p>2018</p>
            <p>Staff Departemen Keilmuan BEM Fasilkom UI</p>
          </li>
          <li class="list-group-item">
            <p>2018</p>
            <p>Wakil Penanggung Jawab E-Vote Pemira UI</p>
          </li>
          <li class="list-group-item">
            <p>2017 - 2018</p>
            <p>Ketua Teen Ministry GKRI Dwiwarna</p>
          </li>
          <li class="list-group-item">
            <p>2018</p>
            <p>Staff of Food and Beverage at Compfest</p>
          </li>
          <li class="list-group-item">
            <p>2018</p>
            <p>Staff Danus Retreat Keluarga Fasilkom</p>
          </li>
          <li class="list-group-item">
            <p>2018</p>
            <p>Mentor Orientasi Kehidupan Kampus UI</p>
          </li>
          <li class="list-group-item">
            <p>2018</p>
            <p>Staff Konsumsi Wisuda Genap Fasilkom UI</p>
          </li>
          <li class="list-group-item">
            <p>2018</p>
            <p>Staff LO Wisuda Ganjil Fasilkom UI</p>
          </li>
        </ul>
      </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>